name: 'vam_fashion'
version: '1.0.0'
profile: 'vam_fashion'

model-paths: ["models"]
seed-paths: ["seeds"]

models:
  vam_fashion:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
